
import Navbar from '@/components/Shared/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Shared/Footer/Footer'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app', }

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            {/* className={inter.className} */}
            <body >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
